/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type QuoteSection = {
  _type: "quoteSection";
  quote?: string;
  attribution?: string;
};

export type MediaGroupSection = {
  _type: "mediaGroupSection";
  items?: Array<
    {
      _key: string;
    } & SectionMedia
  >;
  caption?: string;
};

export type MediaSection = {
  _type: "mediaSection";
  media?: SectionMedia;
  fullWidth?: boolean;
};

export type MediaTextSection = {
  _type: "mediaTextSection";
  heading?: string;
  media?: SectionMedia;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mediaPosition?: "left" | "right";
};

export type RichTextSection = {
  _type: "richTextSection";
  heading?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SectionMedia = {
  _type: "sectionMedia";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  alt?: string;
  caption?: string;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "education" | "experience";
  institution?: string;
  degree?: string;
  period?: string;
  location?: string;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  order?: number;
};

export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  order?: number;
  skills?: Array<string>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  year?: number;
  projectType?: string;
  contributors?: Array<string>;
  role?: Array<string>;
  tags?: Array<string>;
  myContribution?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  client?: string;
  location?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  coverVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  sections?: Array<
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & MediaTextSection)
    | ({
        _key: string;
      } & MediaSection)
    | ({
        _key: string;
      } & MediaGroupSection)
    | ({
        _key: string;
      } & QuoteSection)
  >;
  visibility?: boolean;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  gallery?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    alt?: string;
    caption?: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | QuoteSection
  | MediaGroupSection
  | MediaSection
  | MediaTextSection
  | RichTextSection
  | SanityImageAssetReference
  | SanityFileAssetReference
  | SectionMedia
  | Education
  | SkillCategory
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && visibility != false]  | order(coalesce(year, 0) desc, _createdAt desc){  _id,  title,  summary,  year,  projectType,  "slug": slug.current,  "coverImage": coverImage{    ...,    asset->{      _id,      url,      mimeType    }  },  "coverVideo": coverVideo.asset->{ url, mimeType }}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  summary: string | null;
  year: number | null;
  projectType: string | null;
  slug: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  coverVideo: {
    url: string | null;
    mimeType: string | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skillCategory"] | order(order asc){  _id,  title,  order,  skills}
export type SKILLS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  order: number | null;
  skills: Array<string> | null;
}>;

// Source: src/sanity/queries.ts
// Variable: RESUME_QUERY
// Query: *[_type == "education"] | order(order desc){  _id,  type,  institution,  degree,  location,  period,  details,  order}
export type RESUME_QUERY_RESULT = Array<{
  _id: string;
  type: "education" | "experience" | null;
  institution: string | null;
  degree: string | null;
  location: string | null;
  period: string | null;
  details: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  order: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug && visibility != false][0]{  _id,  title,  summary,  role,  tags,  contributors,  "slug": slug.current,  year,  projectType,  client,  location,  links,  "coverImage": {    "url": coalesce(coverImage.asset->url, ""),    "alt": coverImage.alt,    "mimeType": coverImage.asset->mimeType  },  "coverVideo": coverVideo.asset->{ url, mimeType },  "gallery": gallery[]{    alt,    caption,    "image": image.asset->{      url,      mimeType,      "width": metadata.dimensions.width,      "height": metadata.dimensions.height    },    "video": video.asset->{ url, mimeType }  },  myContribution,  "sections": sections[]{    _type,    _key,    _type == "richTextSection" => { heading, content },    _type == "quoteSection" => { quote, attribution },    _type == "mediaTextSection" => {      heading,      content,      mediaPosition,      "media": media{        alt,        caption,        "image": image.asset->{          url,          mimeType,          "width": metadata.dimensions.width,          "height": metadata.dimensions.height        },        "video": video.asset->{ url, mimeType }      }    },    _type == "mediaSection" => {      fullWidth,      "media": media{        alt,        caption,        "image": image.asset->{          url,          mimeType,          "width": metadata.dimensions.width,          "height": metadata.dimensions.height        },        "video": video.asset->{ url, mimeType }      }    },    _type == "mediaGroupSection" => {      caption,      "items": items[]{        alt,        caption,        "image": image.asset->{          url,          mimeType,          "width": metadata.dimensions.width,          "height": metadata.dimensions.height        },        "video": video.asset->{ url, mimeType }      }    }  }}
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  summary: string | null;
  role: Array<string> | null;
  tags: Array<string> | null;
  contributors: Array<string> | null;
  slug: string | null;
  year: number | null;
  projectType: string | null;
  client: string | null;
  location: string | null;
  links: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  coverImage: {
    url: string | "";
    alt: string | null;
    mimeType: string | null;
  };
  coverVideo: {
    url: string | null;
    mimeType: string | null;
  } | null;
  gallery: Array<{
    alt: string | null;
    caption: string | null;
    image: {
      url: string | null;
      mimeType: string | null;
      width: number | null;
      height: number | null;
    } | null;
    video: {
      url: string | null;
      mimeType: string | null;
    } | null;
  }> | null;
  myContribution: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  sections: Array<
    | {
        _type: "mediaGroupSection";
        _key: string;
        caption: string | null;
        items: Array<{
          alt: string | null;
          caption: string | null;
          image: {
            url: string | null;
            mimeType: string | null;
            width: number | null;
            height: number | null;
          } | null;
          video: {
            url: string | null;
            mimeType: string | null;
          } | null;
        }> | null;
      }
    | {
        _type: "mediaSection";
        _key: string;
        fullWidth: boolean | null;
        media: {
          alt: string | null;
          caption: string | null;
          image: {
            url: string | null;
            mimeType: string | null;
            width: number | null;
            height: number | null;
          } | null;
          video: {
            url: string | null;
            mimeType: string | null;
          } | null;
        } | null;
      }
    | {
        _type: "mediaTextSection";
        _key: string;
        heading: string | null;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        mediaPosition: "left" | "right" | null;
        media: {
          alt: string | null;
          caption: string | null;
          image: {
            url: string | null;
            mimeType: string | null;
            width: number | null;
            height: number | null;
          } | null;
          video: {
            url: string | null;
            mimeType: string | null;
          } | null;
        } | null;
      }
    | {
        _type: "quoteSection";
        _key: string;
        quote: string | null;
        attribution: string | null;
      }
    | {
        _type: "richTextSection";
        _key: string;
        heading: string | null;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current) && visibility != false].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_SITEMAP_QUERY
// Query: *[_type == "project" && defined(slug.current) && visibility != false]{  "slug": slug.current,  _updatedAt}
export type PROJECT_SITEMAP_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "project" && visibility != false]\n  | order(coalesce(year, 0) desc, _createdAt desc){\n  _id,\n  title,\n  summary,\n  year,\n  projectType,\n  "slug": slug.current,\n  "coverImage": coverImage{\n    ...,\n    asset->{\n      _id,\n      url,\n      mimeType\n    }\n  },\n  "coverVideo": coverVideo.asset->{ url, mimeType }\n}': PROJECTS_QUERY_RESULT;
    '*[_type == "skillCategory"] | order(order asc){\n  _id,\n  title,\n  order,\n  skills\n}': SKILLS_QUERY_RESULT;
    '*[_type == "education"] | order(order desc){\n  _id,\n  type,\n  institution,\n  degree,\n  location,\n  period,\n  details,\n  order\n}': RESUME_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug && visibility != false][0]{\n  _id,\n  title,\n  summary,\n  role,\n  tags,\n  contributors,\n  "slug": slug.current,\n  year,\n  projectType,\n  client,\n  location,\n  links,\n  "coverImage": {\n    "url": coalesce(coverImage.asset->url, ""),\n    "alt": coverImage.alt,\n    "mimeType": coverImage.asset->mimeType\n  },\n  "coverVideo": coverVideo.asset->{ url, mimeType },\n  "gallery": gallery[]{\n    alt,\n    caption,\n    "image": image.asset->{\n      url,\n      mimeType,\n      "width": metadata.dimensions.width,\n      "height": metadata.dimensions.height\n    },\n    "video": video.asset->{ url, mimeType }\n  },\n  myContribution,\n  "sections": sections[]{\n    _type,\n    _key,\n    _type == "richTextSection" => { heading, content },\n    _type == "quoteSection" => { quote, attribution },\n    _type == "mediaTextSection" => {\n      heading,\n      content,\n      mediaPosition,\n      "media": media{\n        alt,\n        caption,\n        "image": image.asset->{\n          url,\n          mimeType,\n          "width": metadata.dimensions.width,\n          "height": metadata.dimensions.height\n        },\n        "video": video.asset->{ url, mimeType }\n      }\n    },\n    _type == "mediaSection" => {\n      fullWidth,\n      "media": media{\n        alt,\n        caption,\n        "image": image.asset->{\n          url,\n          mimeType,\n          "width": metadata.dimensions.width,\n          "height": metadata.dimensions.height\n        },\n        "video": video.asset->{ url, mimeType }\n      }\n    },\n    _type == "mediaGroupSection" => {\n      caption,\n      "items": items[]{\n        alt,\n        caption,\n        "image": image.asset->{\n          url,\n          mimeType,\n          "width": metadata.dimensions.width,\n          "height": metadata.dimensions.height\n        },\n        "video": video.asset->{ url, mimeType }\n      }\n    }\n  }\n}': PROJECT_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current) && visibility != false].slug.current': PROJECT_SLUGS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current) && visibility != false]{\n  "slug": slug.current,\n  _updatedAt\n}': PROJECT_SITEMAP_QUERY_RESULT;
  }
}
